
//Allowed Objects
dayz_allowedObjects = ["MetalFloor_Preview_DZ","TentStorage","TentStorageDomed","TentStorageDomed2", "VaultStorageLocked", "Hedgehog_DZ", "Sandbag1_DZ","BagFenceRound_DZ","TrapBear","Fort_RazorWire","WoodGate_DZ","Land_HBarrier1_DZ","Land_HBarrier3_DZ","Land_HBarrier5_DZ","Fence_corrugated_DZ","M240Nest_DZ","CanvasHut_DZ","ParkBench_DZ","MetalGate_DZ","OutHouse_DZ","Wooden_shed_DZ","WoodShack_DZ","StorageShed_DZ","Plastic_Pole_EP1_DZ","Generator_DZ","StickFence_DZ","LightPole_DZ","FuelPump_DZ","DesertCamoNet_DZ","ForestCamoNet_DZ","DesertLargeCamoNet_DZ","ForestLargeCamoNet_DZ","SandNest_DZ","DeerStand_DZ","MetalPanel_DZ","WorkBench_DZ","WoodFloor_DZ","WoodLargeWall_DZ","WoodLargeWallDoor_DZ","WoodLargeWallWin_DZ","WoodSmallWall_DZ","WoodSmallWallWin_DZ","WoodSmallWallDoor_DZ","LockboxStorageLocked","WoodFloorHalf_DZ","WoodFloorQuarter_DZ","WoodStairs_DZ","WoodStairsSans_DZ","WoodStairsRails_DZ","WoodSmallWallThird_DZ","WoodLadder_DZ","Land_DZE_GarageWoodDoor","Land_DZE_LargeWoodDoor","Land_DZE_WoodDoor","Land_DZE_GarageWoodDoorLocked","Land_DZE_LargeWoodDoorLocked","Land_DZE_WoodDoorLocked","CinderWallHalf_DZ","CinderWall_DZ","CinderWallDoorway_DZ","CinderWallDoor_DZ","CinderWallDoorLocked_DZ","CinderWallSmallDoorway_DZ","CinderWallDoorSmall_DZ","CinderWallDoorSmallLocked_DZ","MetalFloor_DZ","WoodRamp_DZ","GunRack_DZ","FireBarrel_DZ","WoodCrate_DZ","Scaffolding_DZ"];

//Player self-action handles
dayz_resetSelfActions = {
	s_player_fire =			-1;
	s_player_cook =			-1;
	s_player_boil =			-1;
	s_player_fireout =		-1;
	s_player_butcher =		-1;
	s_player_packtent = 	-1;
	s_player_packvault = 	-1;
	s_player_lockvault = 	-1;
	s_player_unlockvault = 	-1;
	s_player_fillwater =	-1;
	s_player_fillwater2 = 	-1;
	s_player_fillfuel = 	-1;
	s_player_grabflare = 	-1;
	s_player_callzombies = 	-1;
	s_player_showname = 	-1;
	s_player_debuglootpos = 	-1;
	s_player_pzombiesattack = 	-1;
	s_player_pzombiesvision =	-1;
	s_player_pzombiesfeed = 	-1;
	s_player_removeflare = 	-1;
	s_player_painkiller =	-1;
	s_player_studybody = 	-1;
	s_player_tamedog =		-1;
	s_player_madsci_crtl =	-1;
	s_player_parts_crtl =	-1;
	s_build_Sandbag1_DZ = 	-1;
	s_build_Hedgehog_DZ =	-1;
	s_build_Wire_cat1 =		-1;
	s_player_deleteBuild =	-1;
	s_player_forceSave = 	-1;
	s_player_checkGear = 	-1;
	s_player_flipveh = 		-1;
	s_player_stats =		-1;
	s_player_sleep =		-1;
	s_player_movedog =		-1;
	s_player_speeddog =		-1;
	s_player_calldog = 		-1;
	s_player_feeddog = 		-1;
	s_player_waterdog = 	-1;
	s_player_staydog = 		-1;
	s_player_trackdog = 	-1;
	s_player_barkdog = 		-1;
	s_player_warndog = 		-1;
	s_player_followdog = 	-1;
	s_player_repair_crtl =  -1;
	s_player_information =  -1;
	s_player_fuelauto    =  -1;
	s_player_fuelauto2    =  -1;
	s_player_fillgen	 =  -1;
	s_player_upgrade_build	 =  -1;
	s_player_maint_build	 =  -1;
	s_player_downgrade_build	 =  -1;
	s_player_towing		 =  -1;
	s_halo_action =         -1;
	s_player_SurrenderedGear = -1;
	s_player_maintain_area = -1;
	s_player_maintain_area_preview = -1;
	s_player_heli_lift = -1;
	s_player_heli_detach = -1;
	s_player_lockUnlock_crtl = -1;
	s_player_deploybike1 = -1;
	s_player_deploybike2 = -1;
	s_player_deploybike3 = -1;
	s_player_deploybike4 = -1;
	s_player_deploybike5 = -1;
	s_player_deploybike6 = -1;
	s_player_arrest  = -1;
	s_player_drinkwater  = -1;
	s_player_elevator_next = -1;
	s_player_elevator_previous = -1;
	s_player_elevator_select = -1;
	s_player_elevator_upgrade = -1;
	s_player_elevator_upgrade_stop = -1;
	s_player_elevator_call = -1;
	s_player_elevator_id = -1;
	s_player_release = -1;
	zombieBait = -1;
	zombieBomb = -1;
	zombieShield = -1;
	mv22_fold = -1;
	mv22_unfold = -1;
	mv22_open = -1;
	mv22_close = -1;
	suv_close = -1;
	suv_open = -1;
	s_player_butcher_human = -1;
};
call dayz_resetSelfActions;

//Paintable vehicles
ColourVehicles = [
"Mi17_Ins",
"Mi17_Civilian",
"Mi17_CDF",
"UH60M_EP1_DZE",
"GNT_C185C",
"GNT_C185T",
"Mi17_medevac_Ins",
"GNT_C185E",
"GNT_C185F",
"GNT_C185U",
"GNT_C185R",
"GNT_C185",
"ori_pragaCopter_green",
"ori_pragaCopter_yellow",
"Mi17_medevac_CDF",
"UH60M_EP1_DZ",
"Mi17_Ins",
"Mi17_Civilian",
"Mi17_CDF",
"UH60M_EP1_DZE",
"GNT_C185C",
"GNT_C185T",
"Mi17_medevac_Ins",
"GNT_C185E",
"GNT_C185F",
"GNT_C185U",
"GNT_C185R",
"GNT_C185",
"ori_pragaCopter_green",
"ori_pragaCopter_yellow",
"Mi17_medevac_CDF",
"UH60M_EP1_DZ",
"UH60M_EP1_DZ",
"C130J_US_EP1_DZ",
"AH6X_DZ",
"MH6J_DZ",
"Mi17_Civilian_DZ",
"UH60M_EP1_DZE",
"AH6J_EP1_DZE",
"AH6J_EP1_DZ",
"An2_2_TK_CIV_EP1",
"Su39",
"AH6X_EP1",
"Ka52Black",
"MH6J_EP1",
"An2_1_TK_CIV_EP1",
"C130J",
"Su25_Ins",
"Ka52",
"AH6J_EP1",
"Mi17_UN_CDF_EP1",
"UH60M_MEV_EP1",
"UH60M_EP1",
"UH1H_TK_EP1",
"Mi171Sh_rockets_CZ_EP1",
"Mi17_TK_EP1",
"pook_H13_civ_white",
"pook_H13_civ_ru_white",
"pook_H13_medevac_CDF",
"pook_H13_medevac_INS",
"pook_H13_medevac_GUE",
"pook_H13_amphib",
"pook_H13_amphib_GUE",
"pook_H13_amphib_CIV",
"pook_H13_gunship_CDF",
"pook_H13_gunship_GUE",
"pook_H13_transport_GUE",
"pook_H13_civ_black",
"pook_H13_medevac_CIV",
"pook_H13_amphib_CIV_RU",
"pook_H13_gunship_UNO",
"pook_H13_transport_TAK",
"pook_H13_transport_INS",
"pook_H13_civ_yellow",
"pook_H13_transport",
"pook_H13_civ",
"pook_H13_civ_ru_slate",
"pook_H13_transport_CDF",
"pook_H13_transport_UNO",
"pook_H13_amphib_UNO",
"pook_H13_amphib_TAK",
"pook_H13_amphib_PMC",
"pook_H13_civ_ru_yellow",
"pook_H13_gunship",
"pook_H13_gunship_TAK",
"pook_H13_medevac",
"pook_H13_medevac_UNO",
"pook_H13_medevac_TAK",
"pook_H13_medevac_CIV_RU",
"pook_H13_medevac_PMC",
"pook_H13_amphib_CDF",
"pook_H13_amphib_INS",
"pook_H13_gunship_PMC",
"pook_H13_gunship_INS",
"pook_H13_transport_PMC",
"pook_H13_civ_slate",
"pook_H13_civ_ru",
"pook_H13_civ_ru_black",
"ZSU_INS",
"BMP2_Ambul_CDF",
"BMP2_HQ_INS",
"BMP2_HQ_CDF",
"BMP2_Ambul_INS",
"BMP2_CDF",
"BMP2_Gue",
"BMP2_INS",
"car_sedan",
"Ural_ZU23_INS",
"Ural_ZU23_Gue",
"UralRefuel_INS",
"BRDM2_Gue",
"BRDM2_ATGM_CDF",
"UAZ_INS",
"UAZ_RU",
"car_hatchback",
"GLT_M300_LT",
"GLT_M300_ST",
"ori_ScrapBuggy",
"Ural_ZU23_CDF",
"Ural_INS",
"Ural_CDF",
"UralOpen_CDF",
"UralOpen_INS",
"UralCivil",
"UralCivil2",
"UralRefuel_CDF",
"UralRepair_CDF",
"UralRepair_INS",
"UralReammo_CDF",
"UralReammo_INS",
"BRDM2_HQ_Gue",
"BRDM2_CDF",
"BRDM2_INS",
"BRDM2_ATGM_INS",
"HMMWV",
"HMMWV_M2",
"HMMWV_TOW",
"HMMWV_MK19",
"UAZ_CDF",
"Offroad_DSHKM_INS",
"Pickup_PK_GUE",
"UAZ_MG_CDF",
"UAZ_MG_INS",
"UAZ_AGS30_RU",
"UAZ_AGS30_CDF",
"UAZ_AGS30_INS",
"hilux1_civil_1_open",
"Offroad_SPG9_Gue",
"datsun1_civil_1_open",
"UAZ_SPG9_INS",
"Skoda",
"Pickup_PK_INS",
"Offroad_DSHKM_Gue",
"HMMWV_Ambulance_DES_EP1",
"UralSalvage_TK_EP1",
"Offroad_DSHKM_TK_GUE_EP1",
"Offroad_SPG9_TK_GUE_EP1",
"HMMWV_MK19_DES_EP1",
"TT650_TK_CIV_EP1",
"MtvrReammo_DES_EP1",
"UAZ_AGS30_TK_EP1",
"UAZ_Unarmed_UN_EP1",
"Ural_UN_EP1",
"UralRepair_TK_EP1",
"HMMWV_Ambulance_CZ_DES_EP1",
"HMMWV_Avenger_DES_EP1",
"M1030_US_DES_EP1",
"MtvrSupply_DES_EP1",
"Lada1_TK_CIV_EP1",
"AAV",
"Ikarus",
"Ural_ZU23_TK_EP1",
"Ural_ZU23_TK_GUE_EP1",
"LAV25_HQ",
"V3S_Gue",
"V3S_Civ",
"Kamaz",
"HMMWV_Avenger",
"Ural_TK_CIV_EP1",
"UralSupply_TK_EP1",
"MTVR",
"LAV25",
"KamazReammo",
"KamazRepair",
"KamazRefuel",
"UralRefuel_TK_EP1",
"UralReammo_TK_EP1",
"MtvrRefuel",
"MtvrReammo",
"MtvrRepair",
"HMMWV_Armored",
"UAZ_Unarmed_TK_CIV_EP1",
"UAZ_Unarmed_TK_EP1",
"HMMWV_Ambulance",
"Pickup_PK_TK_GUE_EP1",
"UAZ_MG_TK_EP1",
"Lada2",
"VWGolf",
"M1030",
"TT650_TK_EP1",
"TT650_Gue",
"TT650_Civ",
"TT650_Ins",
"MMT_Civ",
"MtvrRepair_DES_EP1",
"MtvrSalvage_DES_EP1",
"HMMWV_DES_EP1",
"MTVR_DES_EP1",
"MtvrRefuel_DES_EP1",
"Lada2_TK_CIV_EP1",
"Pickup_PK_INS_DZE4",
"Pickup_PK_INS_DZE2",
"Offroad_DSHKM_Gue_DZE",
"Offroad_DSHKM_Gue_DZE2",
"M1126_ICV_mk19_EP1",
"M1130_CV_EP1",
"HMMWV_M1151_M2_CZ_DES_EP1_DZ",
"SUV_TK_CIV_EP1",
"SUV_TK_EP1",
"BTR40_MG_TK_INS_EP1",
"Offroad_DSHKM_Gue_DZ",
"Offroad_DSHKM_Gue_DZE3",
"ori_transit",
"Pickup_PK_INS_DZE1",
"Pickup_PK_GUE_DZE4",
"Pickup_PK_GUE_DZE",
"Pickup_PK_TK_GUE_EP1_DZE",
"VolhaLimo_TK_CIV_EP1",
"ori_poldek",
"ori_titanic",
"ori_survivorBus",
"Ikarus_TK_CIV_EP1",
"M1126_ICV_M2_EP1",
"M1129_MC_EP1",
"M1128_MGS_EP1",
"GRAD_TK_EP1",
"BRDM2_HQ_TK_GUE_EP1",
"BRDM2_TK_EP1",
"BRDM2_TK_GUE_EP1",
"HMMWV_M1151_M2_CZ_DES_EP1_DZE",
"BRDM2_ATGM_TK_EP1",
"HMMWV_M998A2_SOV_DES_EP1_DZE",
"SUV_PMC",
"SUV_UN_EP1",
"BTR40_MG_TK_GUE_EP1",
"BTR40_TK_INS_EP1",
"BTR40_TK_GUE_EP1",
"Pickup_PK_INS_DZE3",
"Pickup_PK_TK_GUE_EP1_DZE4",
"Pickup_PK_GUE_DZ",
"Pickup_PK_TK_GUE_EP1_DZE2",
"HMMWV_M1035_DES_EP1",
"hilux1_civil_3_open_EP1",
"S1203_ambulance_EP1",
"S1203_TK_CIV_EP1",
"ori_vil_lada_2105_rust",
"ori_poldek_black",
"Old_moto_TK_Civ_EP1",
"ATV_US_EP1",
"ATV_CZ_EP1",
"Old_bike_TK_INS_EP1",
"HMMWV_M998A2_SOV_DES_EP1_DZ",
"UAZ_MG_TK_EP1_DZE",
"Pickup_PK_TK_GUE_EP1_DZ",
"Pickup_PK_TK_GUE_EP1_DZE1",
"Pickup_PK_GUE_DZE2",
"Offroad_DSHKM_Gue_DZE1",
"M1135_ATGMV_EP1",
"M1133_MEV_EP1",
"ori_vil_originsmod_truck_civ",
"HMMWV_DZ",
"SUV_Special",
"Offroad_DSHKM_Gue_DZE4",
"ori_vil_originsmod_lublin_truck",
"Pickup_PK_INS_DZ",
"Pickup_PK_GUE_DZE1",
"Pickup_PK_GUE_DZE3",
"Pickup_PK_TK_GUE_EP1_DZE3",
"UAZ_MG_TK_EP1_DZ",
"Volha_2_TK_CIV_EP1",
"BTR90_DZE",
"UralCivil2_DZE",
"LAV25_DZE",
"LAV25_DZ",
"UAZ_RU_DZE3",
"UAZ_INS_DZE3",
"UAZ_CDF_DZE2",
"UAZ_RU_DZE1",
"UAZ_CDF_DZE1",
"hilux1_civil_1_open_DZE3",
"hilux1_civil_1_open_DZE2",
"hilux1_civil_1_open_DZE",
"car_sedan_DZE1",
"car_sedan_DZE2",
"datsun1_civil_1_open_DZE2",
"datsun1_civil_1_open_DZE4",
"car_hatchback_DZE3",
"Lada2_DZE2",
"Lada2_DZE1",
"Lada2_TK_CIV_EP1_DZE2",
"Lada2_TK_CIV_EP1_DZE4",
"VolhaLimo_TK_CIV_EP1_DZE3",
"VolhaLimo_TK_CIV_EP1_DZE4",
"VWGolf_DZE1",
"Skoda_DZE2",
"BTR90_HQ_DZ",
"BTR90_HQ_DZE",
"LAV25_HQ_DZ",
"BTR90_DZ",
"UralCivil_DZE",
"V3S_RA_TK_GUE_EP1_DZE",
"MtvrRefuel_DES_EP1_DZ",
"UAZ_Unarmed_TK_EP1_DZE3",
"UAZ_INS_DZE1",
"UAZ_Unarmed_UN_EP1_DZE4",
"UAZ_Unarmed_TK_CIV_EP1_DZE4",
"UAZ_Unarmed_TK_CIV_EP1_DZE3",
"UAZ_Unarmed_TK_EP1_DZE1",
"UAZ_RU_DZE4",
"UAZ_INS_DZE2",
"UAZ_Unarmed_TK_CIV_EP1_DZE1",
"hilux1_civil_1_open_DZE1",
"car_sedan_DZE4",
"datsun1_civil_1_open_DZE3",
"datsun1_civil_1_open_DZE",
"car_hatchback_DZE1",
"car_hatchback_DZE3",
"Lada2_DZE4",
"Volha_2_TK_CIV_EP1_DZE2",
"Volha_2_TK_CIV_EP1_DZE3",
"Volha_2_TK_CIV_EP1_DZE1",
"Skoda_DZE1",
"KamazOpen_DZE",
"V3S_Refuel_TK_GUE_EP1",
"UAZ_Unarmed_TK_EP1_DZE4",
"UAZ_Unarmed_UN_EP1_DZE3",
"UAZ_INS_DZE4",
"UAZ_CDF_DZE4",
"UAZ_Unarmed_UN_EP1_DZE2",
"UAZ_Unarmed_TK_EP1_DZE2",
"car_hatchback_DZE2",
"Lada1_TK_CIV_EP1_DZE4",
"Lada1_TK_CIV_EP1_DZE1",
"Lada2_TK_CIV_EP1_DZE3",
"Lada2_DZE3",
"VolhaLimo_TK_CIV_EP1_DZE3",
"VolhaLimo_TK_CIV_EP1_DZE2",
"VWGolf_DZE3",
"Skoda_DZE3",
"LAV25_HQ_DZE",
"UAZ_Unarmed_UN_EP1_DZE2",
"UAZ_Unarmed_UN_EP1_DZE1",
"UAZ_CDF_DZE3",
"UAZ_RU_DZE2",
"hilux1_civil_1_open_DZE4",
"car_sedan_DZE3",
"datsun1_civil_1_open_DZE1",
"car_hatchback_DZE4",
"Lada2_TK_CIV_EP1_DZE1",
"Lada1_TK_CIV_EP1_DZE2",
"Lada1_TK_CIV_EP1_DZE3",
"VolhaLimo_TK_CIV_EP1_DZE1",
"Volha_2_TK_CIV_EP1_DZE4",
"VWGolf_DZE2",
"VWGolf_DZE4",
"Skoda_DZE4",
"M1A2_US_TUSK_MG_EP1",
"WarfareSalvageTruck_RU",
"WarfareRepairTruck_Gue",
"V3S_TK_GUE_EP1",
"BMP2_UN_EP1",
"WarfareSalvageTruck_Gue",
"WarfareSalvageTruck_USMC",
"WarfareReammoTruck_CDF",
"M113_UN_EP1_DZ",
"M113_TK_EP1",
"M113Ambul_UN_EP1",
"SUV_Orange_DZE1",
"SUV_Red_DZE2",
"SUV_Yellow",
"SUV_Charcoal_DZE3",
"SUV_Camo",
"SUV_White_DZE4",
"SUV_Silver_DZE4",
"SUV_TK_CIV_EP1_DZE2",
"SUV_Charcoal_DZE2",
"SUV_Yellow_DZE1",
"SUV_Green_DZE1",
"SUV_Camo_DZE1",
"SUV_Orange",
"SUV_Pink",
"SUV_White",
"SUV_Red",
"SUV_Yellow_DZE3",
"SUV_Orange_DZE2",
"SUV_Silver_DZE2",
"SUV_PMC_BAF",
"SUV_TK_CIV_EP1_DZE3",
"SUV_Silver_DZE3",
"BAF_ATV_D",
"T72_TK_EP1",
"T34_TK_EP1",
"WarfareSupplyTruck_CDF",
"WarfareSupplyTruck_Gue",
"WarfareSalvageTruck_INS",
"WarfareReammoTruck_RU",
"V3S_Salvage_TK_GUE_EP1",
"WarfareReammoTruck_USMC",
"SUV_Green_DZE2",
"SUV_TK_CIV_EP1_DZE4",
"SUV_Red_DZE3",
"SUV_White_DZE2",
"SUV_Pink_DZE4",
"SUV_Green_DZE4",
"SUV_Pink_DZE1",
"SUV_White_DZE1",
"SUV_Blue_DZE4",
"BMP2_HQ_TK_EP1",
"M1A1_US_DES_EP1",
"BMP2_TK_EP1",
"WarfareSupplyTruck_RU",
"WarfareSupplyTruck_INS",
"WarfareSupplyTruck_USMC",
"V3S_Reammo_TK_GUE_EP1",
"M113_UN_EP1",
"M113_UN_EP1_DZE",
"M113_TK_EP1_DZ",
"SUV_Camo_DZE4",
"SUV_Red_DZE4",
"SUV_Pink_DZE3",
"SUV_Green_DZE3",
"SUV_Orange_DZE4",
"SUV_Red_DZE1",
"SUV_Camo_DZE3",
"SUV_Blue_DZE2",
"SUV_Camo_DZE2",
"SUV_Charcoal_DZE1",
"SUV_White_DZE3",
"SUV_TK_CIV_EP1_DZE1",
"SUV_Silver",
"SUV_Charcoal",
"SUV_Green",
"SUV_Blue",
"T55_TK_GUE_EP1",
"V3S_Open_TK_CIV_EP1",
"V3S_TK_GUE_EP1",
"V3S_Supply_TK_GUE_EP1",
"WarfareSalvageTruck_CDF",
"WarfareReammoTruck_Gue",
"WarfareReammoTruck_INS",
"M113_UN_EP1_DZE",
"M113_TK_EP1_DZE",
"M113Ambul_TK_EP1",
"SUV_Orange_DZE3",
"SUV_Charcoal_DZE4",
"SUV_Blue_DZE3",
"SUV_Pink_DZE2",
"SUV_Yellow_DZE2",
"SUV_Silver_DZE1",
"SUV_Blue_DZE1",
"SUV_Yellow_DZE4",
"BAF_ATV_W",
"JetSkiYanahui_Yellow",
"JetSkiYanahui_Red",
"JetSkiYanahui_Blue",
"JetSkiYanahui_Green" 
];